### ISSUE TITLE
System Maintenance

### ISSUE THREAD

**Issue by phernandoe** [kpomer/stick_E_notes#15]
-Javadocs
-Comments
-Ordering Functions correctly

**Comment by kpomer** [comment]
Done when code can be cleanly reviewed and read to understand how functions work

**Comment by kpomer** [comment]
Issues to fix:
-Add Card option sometimes jumps back to "Enter a command".  Not sure why

**Comment by kpomer** [comment]
30 min - Added Javadoc comments to complex functions

**Comment by kpomer** [comment]
15 min - Deleted extra Scanners in UserInterface.  Set all to "reader"

**Comment by kpomer** [comment]
1 hr - Found and fixed an issue where nextInt() does not allow user to input values during their next input.  Problem has been fixed and merged
