### ISSUE TITLE
Edit Card Fields (after creating card)

### ISSUE THREAD

**Issue by kpomer** [kpomer/stick_E_notes#17]

**Comment by yemo06** [comment]
Edit the name
Edit DESCRIPTION
cHANGE COLOR

**Comment by yemo06** [comment]
If time allows be able to change due date/ Deadline

**Comment by kpomer** [comment]
Worked for 3 hrs to test/create functionality 4/3

**Comment by kpomer** [comment]
0.25 hrs - 4/4
Confirmed that tests pass and issued pull request to merge it into master

**Comment by kpomer** [comment]
0.75 hrs - 4/6
Writing tests/editing addCardTest from test failures

**Comment by kpomer** [comment]
1.5 hrs - 4/6
All tests pass (I had to change addCard/editCard/changePriority functions
