### ISSUE TITLE
Be able to view the contents of a Card

### ISSUE THREAD

**Issue by kpomer** [kpomer/stick_E_notes#20]
See Card from command Line (using Index)

**Comment by keselh54** [comment]
Done when the toString function can print the information in the following format:
"ID: "+iD+"Title: "+title+"; Description: "+description+"; Deadline: "+deadline

Test by seeing if it can print this even if fields are missing.

**Comment by keselh54** [comment]
you can create a card, and call the viewCard method to show all the details of the card in the format show in the comment above. All tests passed. (It took 2 hours)
