### ISSUE TITLE
edit card- when adding a card

### ISSUE THREAD

**Issue by keselh54** [kpomer/stick_E_notes#35]
when adding a card, it will ask for a title, but then ask for edits? and if the user says yes to edits, then the other fields of the card can be filled in.

**Comment by kpomer** [comment]
-Prompt name/description
-Do you want to add other fields? (y/n)

**Comment by kpomer** [comment]
4/10 - 1 hr
I spent an hour creating functionality for adding a card.  Now when a user adds a card, it asks for the Title and Priority and then asks to see if the user would like to add any new info, which they can deny or accept
